### ISSUE TITLE
Potential API Key Leak

### ISSUE THREAD

**Issue by BetaDoggo** [gokayfem/ComfyUI-FLUX-fal-API#1]
When a custom string is entered into a comfyui node the string is saved in the metadata of the output image. If a user shares an image created with this node online with metadata intact anyone viewing the image will be able to load the image in their own instance and steal the api key.
Here's the metadata from one of the images made with this node:
```
{
  "11": {
    "class_type": "SaveImage",
    "inputs": {
      "filename_prefix": "flux",
      "images": [
        "40",
        0
      ]
    }
  },
  "40": {
    "class_type": "FluxSchnell_fal",
    "inputs": {
      "api_key": "00000000-00000-0000-0000-000000000000:00000000000000000000000000000000",
      "enable_safety_checker": true,
      "image_size": "landscape_4_3",
      "num_images": 1,
      "num_inference_steps": 4,
      "prompt": "anime girl",
      "seed": -1
    }
  }
}
```
The api key can be read from the inputs section (I zeroed it out for obvious reasons).

I recommend either altering the node so that it loads the key from a file instead or adding a disclaimer about stripping metadata.

**Comment by gokayfem** [comment]
Fixed thanks for the warning!
