### ISSUE TITLE
custom resolution?

### ISSUE THREAD

**Issue by festivus37** [gokayfem/ComfyUI-FLUX-fal-API#2]
Hi, thanks for putting this together. Is it possible to have a custom resolution option like on fal.ai? The max 16:9 resolution I can do with this is 1024x576. but on their website I can do 1344x768, 1536x896 etc.  Is it possible to get an option for that?  Thanks again.
![image](https://github.com/user-attachments/assets/d1857b69-af53-4494-84b0-d0a3ce933e57)

**Comment by gokayfem** [comment]
Done!
